#!/bin/bash
# pmcambpell
# 2020-10-03
# feedback for assign 1
# copy html generated by assess.py into their 
#  home directory

# list of all files
echo " must be run as root as you are copying into their home directoreies"
list=`ls *.html|cut -f 1 -d '-'`
# for i in angela antonio ; do
for i in $list ; do
    cp $i-feedback-ass1.html /home/$i/www/
done
