#!/bin/bash
# pmcambpell
# 2020-10-03
# feedback for assign 1
# copy html generated by assess.py into their 
#  home directory

# list of all files
htmlname="project1"
echo " must be run as root as you are copying into their home directoreies"
list=`ls *.html|cut -f 1 -d '-'`
# for i in angela antonio ; do
for i in $list ; do
    html=$i-feedback-$htmlname.html
    cp $html /home/$i/www/
    chown $i:js2020 /home/$i/www/$html
done
